### PR TITLE
implemented dark/light theme mode

### LINKED ISSUE #107: Implement dark/light theme mode into the web app

### PR DESCRIPTION
**Pull request by 7malikk**
## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update
- [ ] Other: 
  
   
## Description of what this Pull Request does
Implemented dark/light theme mode in the app

## Related Tickets & Documents
- Fixes #107 

## QA Instructions, Screenshots, Recordings
dark-light

### CODE REVIEW

**Comment by 7malikk** [comment]
@annonymousauthority I've made changes to my PR 

I'd also like to point something out

I noticed you made some changes in the `welcome_comp` a ton of commits back and currently the welcome page looks like this on 1440px screen;

image

What are your thoughts?

I made changes for the purpose of the recording alone

**Comment by annonymousauthority** [comment]
LGTM!

**Review by annonymousauthority — DISMISSED** [review]
LG!

**Review by annonymousauthority — APPROVED** [review]
LGTG

**Pull request merged**
