### PR TITLE
New Feature:  Editor Tab Renaming

### PR DESCRIPTION
**Pull request by babblebey**
This PR introduces a new functionality that allows users to rename tabs in the project. I have enhanced the existing code to provide a seamless tab renaming thing.

**Changes Made:**
The following changes have been made to implement the tab renaming functionality:
1. Added the `handleTabRename` function, which handles the tab renaming process.
2. When a user initiates the renaming process by double-clicking on a tab, a form with an input field is dynamically created to collect the new tab name.
3. The user can enter the desired name in the input field and submit the form to trigger the `setTabName`  through the `tabRenameSubmitHandler` function.
4. The `setTabName` function updates the `items` state by mapping over the existing items, modifying the title of the targeted tab with the new name and in turn updates it in `localStorage`.
5. The tab's content is updated to reflect the new name.
6. Additionally, a `onFocucOut` event listener has been added to handle cases where the user clicks away from the tab while renaming. It keeps the tab name as is and all event listeners are cleaned.

**Testing:**
Verify that the following scenarios have been tested and produce the expected results:
- Renaming a tab and verifying that the new name is reflected in the UI, the `items` state and the localStorage `barItems`
- Canceling the renaming process by clicking away from the tab and ensuring that the original name is restored.
- Renaming multiple tabs simultaneously and confirming that each tab is updated correctly.

Please review and merge this pull request to incorporate this functionality into the project.

### CODE REVIEW

**Review by annonymousauthority — APPROVED** [review]
LGTM

**Comment by annonymousauthority** [comment]
Fix conflicts @babblebey

**Comment by annonymousauthority** [comment]
> Conflict resolved sir!!!

Could you pull from main just to be sure you're up to date before merge?

**Comment by babblebey** [comment]
> > Conflict resolved sir!!!
> 
> Could you pull from main just to be sure you're up to date before merge?

Yes sir.! See PR #153

**Review by annonymousauthority — APPROVED** [review]
Update

**Comment by babblebey** [comment]
PR Merged, Closes Issue at #80

**Pull request merged**
