### PR TITLE
Taylor - Updating Signup Form Functionality

### LINKED ISSUE #173: Taylor - Create a function that signs in a user
- Creating a function that signs in a user from their chosen authenticated method: email, Google, or GitHub

### PR DESCRIPTION
**Pull request by TaylorDJones11**
## Description of what this Pull Request does
- Updates the Form Validation to catch whitespace in input fields
- pushing users and their information to the 'CODERS' database
-  Email Verification function is in this PR but needs onboarding to be merged to connect
- Adding a functional close button to form

## Related Tickets & Documents
- Closes #173 

## Screenshots
SignupForm

### CODE REVIEW

**Review by Remi-dee — APPROVED** [review]
LG

**Comment by TaylorDJones11** [comment]
@annonymousauthority this PR needs a review. Also, it looks like Dipo's PR is actually re-doing the work I created in this PR. So which one of us is supposed to be doing this?

**Review by Remi-dee — APPROVED** [review]
LGTM

**Review by annonymousauthority — APPROVED** [review]
Cautionary merge

**Review by annonymousauthority — APPROVED** [review]
LG

**Review by Remi-dee — APPROVED** [review]
LG

**Pull request merged**
